main:
  - name: 진료철학
    url: 'philosophy/'
    weight: 10
  - name: 진료과목
    url: 'treatments/'
    weight: 20
  - name: 치료사례
    url: 'reviews/'
    weight: 30
  - name: 원장 칼럼
    url: 'blog/'
    weight: 40
  - name: 온라인문의
    url: 'inquiry/'
    weight: 45
  - name: 상담예약
    url: '#location'
    weight: 50
