const assert = require('assert');
const fs = require('fs');
const path = require('path');
const { CLINIC_EVALUATION, checkClinicFacts, prepareArticleKnowledge } = require('../scripts/auto_column/medical_policy');
const { validateArticleContent } = require('../scripts/auto_column/content_validator');

const root = path.join(__dirname, '..');
const slug = 'seongnam-main-syncope-subway-dizziness';
const markdown = fs.readFileSync(path.join(root, 'content/blog', `${slug}.md`), 'utf8');
const body = markdown.replace(/^---[\s\S]*?---\s*/, '');
const condition = fs.readFileSync(path.join(root, 'content/conditions/syncope.md'), 'utf8');
const knowledge = require('../scripts/auto_column/medical_knowledge/syncope.json');
const nhs = 'https://www.nhs.uk/symptoms/fainting/';
const kdca = 'https://health.kdca.go.kr/healthinfo/biz/health/gnrlzHealthInfo/gnrlzHealthInfo/gnrlzHealthInfoView.do?cntnts_sn=6226';
const section = heading => body.split(`## ${heading}\n`)[1]?.split('\n## ')[0];
const emergency = section('즉시 119 도움이 필요한 상황');
const followup = section('모든 실신을 미주신경성 실신으로 단정해서는 안 됩니다');
const records = section('진료 전 준비할 기록표');

assert(emergency && followup && records, 'emergency, recovered-patient evaluation and record preparation must be distinct sections');
assert(emergency.includes('깨워도 반응이 없는') && emergency.includes('즉시 119'));
assert(emergency.includes('정상적으로 숨 쉬지 않거나 호흡 여부가 불확실'));
assert(emergency.includes('상담원의 지시에 따라 가슴압박과 자동심장충격기'));
for (const symptom of ['회복되지', '가슴 통증', '운동하는 도중', '누워 있는 상태', '큰 부상']) assert(emergency.includes(symptom));
assert(emergency.includes(kdca) && emergency.includes(nhs), 'claims need relevant sources in the explanation');
assert(!emergency.includes('1분') && !emergency.includes('순환기내과'), 'an unresponsive person may not be told to wait or book outpatient care');
assert(followup.includes('처음 의식을 잃었거나') && followup.includes('가족력'));
assert(body.includes(CLINIC_EVALUATION));
assert(body.includes('이러한 참고 검사는 실신 원인을 확진하거나 심전도, 기립성 혈압, 심장·신경계 평가를 대신하지 않습니다'));
assert(condition.includes('심전도, 기립성 혈압, 심장·신경계 평가를 대신하지 않습니다'));
assert(!body.includes('스트레스 척도와 체질 맥진'));
assert(checkClinicFacts(body, 'syncope').valid);
assert(body.includes('의료진에게 배운 경우') && !body.includes('서 있어야만 한다면'));
assert(records.includes('‘모름’') && records.includes('추측해 정확한 수치처럼 적지 않습니다'));
assert(records.includes('본인의 기억과 구분'));
const recordRows = records.split('\n').filter(line => /^\|/.test(line) && !/^\|[-\s|]+\|$/.test(line)).slice(1);
assert.strictEqual(recordRows.length, 7);
assert(records.includes('기록보다 119 도움과 안전 확보가 우선'));
assert(knowledge.evaluationGuidance.startsWith(CLINIC_EVALUATION));
assert(knowledge.specificRules.some(rule => rule.includes('즉시 119') && rule.includes('급성 신호 없이 회복')));
assert(knowledge.specificRules.some(rule => rule.includes('모름·미확인') && rule.includes('목격자')));
const prepared = prepareArticleKnowledge(knowledge, { topicAngle: { id: 'subway-dizziness' } });
assert(prepared.evidenceNotes.some(note => note.sourceUrl === kdca && note.sourceVerified && note.productionUsable));
const validation = validateArticleContent({ title: markdown.match(/^title: "(.+)"/m)[1], summary: markdown.match(/^summary: "(.+)"/m)[1], category: 'syncope', body, diseaseId: 'syncope', geoId: 'seongnam-main', titleDisease: '미주신경성 실신', topicAngle: { id: 'subway-dizziness' }, knowledge: prepared, requireVerifiedSources: true });
assert.deepStrictEqual(validation.errors.filter(error => /verified medical sources|Topic evidence|explanation|Clinic facts/.test(error)), []);
assert(markdown.includes('article_review_status: "source_based"') && !markdown.includes('medical_information_reviewer:'));
assert(markdown.includes('date: 2026-09-30T14:25:20.132+09:00'));
assert(markdown.includes('lastmod: 2026-10-02T15:16:00+09:00'));

if (process.argv[2]) {
  const output = path.resolve(process.argv[2]);
  const html = fs.readFileSync(path.join(output, 'blog', slug, 'index.html'), 'utf8');
  const attributes = tag => Object.fromEntries([...tag.matchAll(/([^\s=]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))/g)].map(m => [m[1], m[2] ?? m[3] ?? m[4]]));
  const tables = [...html.matchAll(/<table\b[^>]*>[\s\S]*?<\/table>/g)];
  const wrappers = [...html.matchAll(/(<div\b[^>]*>)\s*(<table\b[^>]*>[\s\S]*?<\/table>)\s*<\/div>/g)].filter(m => attributes(m[1]).class === 'column-table-scroll');
  assert.strictEqual(tables.length, 2, 'both the recovered-patient and record tables must render');
  assert.strictEqual(wrappers.length, 2);
  assert.strictEqual((html.match(/class=(?:"|')?column-table-scroll(?:"|')?(?:\s|>)/g) || []).length, 2, 'no nested scroll wrappers');
  for (const wrapper of wrappers) assert.strictEqual(attributes(wrapper[1]).tabindex, '0');
  const record = tables.find(table => table[0].includes('기록 항목'))?.[0];
  assert(record && (record.match(/<td\b/g) || []).length === 14);
  assert(!html.includes('**'));
  assert(html.includes('즉시 119 도움이 필요한 상황') && html.includes('진료 전 준비할 기록표'));
  assert(html.includes(kdca.replace(/&/g, '&amp;')) && html.includes(nhs));
  const scripts = [...html.matchAll(/(<script\b[^>]*>)([\s\S]*?)<\/script>/g)].filter(m => attributes(m[1]).type === 'application/ld+json');
  const article = scripts.flatMap(m => JSON.parse(m[2])['@graph'] || []).find(n => n['@type'] === 'Article');
  assert(article && article.author.name === '해아림한의원 의료 콘텐츠팀');
  assert(article.datePublished.startsWith('2026-09-30') && article.dateModified.startsWith('2026-10-02'));
  assert(!article.reviewedBy && !article.contributor);
  assert(html.includes(`https://healimbd.com/blog/${slug}/`));
  const pillar = fs.readFileSync(path.join(output, 'conditions/syncope/index.html'), 'utf8');
  assert(pillar.includes(`/blog/${slug}/`) && pillar.includes('대표 칼럼'));
}
console.log('✅ Syncope emergency versus follow-up guidance, clinic evaluation scope, seven record fields, verified sources, honest metadata and optional Hugo rendering passed.');
