const fs = require('fs');
const assert = require('assert');

console.log('🧪 Starting Treatment Reviews (Firestore & Storage) Security & Logic Test Suite...\n');

let passed = 0;
async function test(name, fn) {
  try {
    await fn();
    console.log(`✅ PASS: ${name}`);
    passed++;
  } catch (err) {
    console.error(`❌ FAIL: ${name}`);
    console.error(err);
    process.exit(1);
  }
}

async function run() {
  // 1. Check firestore.rules file contents
  const firestoreRules = fs.readFileSync('firestore.rules', 'utf8');
  await test('1. firestore.rules contains treatment_reviews with authenticated read and admin-only write', () => {
    assert.ok(firestoreRules.includes('match /treatment_reviews/{reviewId}'), 'treatment_reviews match exists');
    assert.ok(firestoreRules.includes('allow read: if request.auth != null;'), 'read restricted to authenticated users');
    assert.ok(firestoreRules.includes('allow create, update, delete: if isAdmin();'), 'write restricted to isAdmin()');
    assert.ok(!firestoreRules.includes('match /treatment_reviews/{reviewId} {\n      allow read: if true;'), 'Must not allow public read');
  });

  // 2. Check storage.rules file contents
  const storageRules = fs.readFileSync('storage.rules', 'utf8');
  await test('2. storage.rules contains treatment-reviews/{reviewId}/{fileName} with authenticated read and admin-only write', () => {
    assert.ok(storageRules.includes('match /treatment-reviews/{reviewId}/{fileName}'), 'treatment-reviews path exists');
    assert.ok(storageRules.includes('function signedIn()'), 'signedIn helper exists');
    assert.ok(storageRules.includes('function isAdmin()'), 'isAdmin helper exists');
    assert.ok(storageRules.includes('function isValidImageUpload()'), 'isValidImageUpload helper exists');
    assert.ok(storageRules.includes('allow read: if signedIn();'), 'read restricted to signedIn()');
    assert.ok(storageRules.includes('allow create, update: if isAdmin() && isValidImageUpload();'), 'create/update restricted to admin and valid image');
    assert.ok(storageRules.includes('allow delete: if isAdmin();'), 'delete restricted to admin without resource gating');
    assert.ok(storageRules.includes('match /{allPaths=**} {\n      allow read, write: if false;'), 'Default deny exists');
  });

  // 3. Logic: Deterministic Document ID generation for legacy migration
  await test('3. Deterministic ID generation for legacy migration produces idempotent IDs', () => {
    function getDeterministicDocId(legacyId) {
      if (!legacyId || typeof legacyId !== 'string') {
        throw new Error('legacyId is required');
      }
      return 'legacy_' + legacyId.replace(/[^a-zA-Z0-9_-]/g, '_');
    }

    const id1 = 'custom-1725780012345';
    const id2 = 'custom-1725780012345'; // duplicate item
    const id3 = 'custom-1725789999999';

    const docId1 = getDeterministicDocId(id1);
    const docId2 = getDeterministicDocId(id2);
    const docId3 = getDeterministicDocId(id3);

    assert.strictEqual(docId1, 'legacy_custom-1725780012345');
    assert.strictEqual(docId1, docId2, 'Same legacyId must produce identical docId');
    assert.notStrictEqual(docId1, docId3, 'Different legacyId must produce distinct docId');
  });

  // 4. Logic: New admin reviews use random/timestamp ID, NOT legacy prefix
  await test('4. New reviews generated by admin do NOT use legacy prefix', () => {
    function generateNewReviewId() {
      return 'tr_' + Date.now() + '_' + Math.random().toString(36).substr(2, 6);
    }
    const newId = generateNewReviewId();
    assert.ok(newId.startsWith('tr_'), 'Must start with tr_');
    assert.ok(!newId.startsWith('legacy_'), 'Must not start with legacy_');
  });

  // 5. Logic: Deduplication against already-migrated cases
  await test('5. Migration skips items that already exist in Firestore', () => {
    const existingFirestoreDocIds = new Set(['legacy_custom-1', 'legacy_custom-2']);
    const localCases = [
      { id: 'custom-1', title: 'Case 1' },
      { id: 'custom-2', title: 'Case 2' },
      { id: 'custom-3', title: 'Case 3' }
    ];

    function getUnmigratedCases(cases, existingIds) {
      return cases.filter(c => !existingIds.has('legacy_' + c.id.replace(/[^a-zA-Z0-9_-]/g, '_')));
    }

    const unmigrated = getUnmigratedCases(localCases, existingFirestoreDocIds);
    assert.strictEqual(unmigrated.length, 1);
    assert.strictEqual(unmigrated[0].id, 'custom-3');
  });

  // 6. Logic: Base64 to Blob conversion
  await test('6. Base64 data URL correctly parses MIME type and decodes binary', () => {
    const sampleBase64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==';
    const match = sampleBase64.match(/^data:([^;]+);base64,(.+)$/);
    assert.ok(match, 'Must match base64 pattern');
    const mimeType = match[1];
    const base64Data = match[2];
    assert.strictEqual(mimeType, 'image/png');
    const buffer = Buffer.from(base64Data, 'base64');
    assert.strictEqual(buffer.length, 70);
  });

  // 7. Verification: Inspect & Backup functions exist in main.js
  const mainJs = fs.readFileSync('assets/js/main.js', 'utf8');
  await test('7. inspectLocalReviewsData & downloadLocalCasesBackup exist and inspect ID, category, sections, image, size', () => {
    assert.ok(mainJs.includes('function inspectLocalReviewsData()'), 'inspectLocalReviewsData exists');
    assert.ok(mainJs.includes('function downloadLocalCasesBackup()'), 'downloadLocalCasesBackup exists');
    assert.ok(mainJs.includes('function checkAndRenderMigrationUI()'), 'checkAndRenderMigrationUI exists');
    assert.ok(mainJs.includes('function executeCasesMigration()'), 'executeCasesMigration exists');

    const inspectBody = mainJs.match(/function inspectLocalReviewsData\(\) \{([\s\S]*?)\n\}/)[1];
    assert.ok(inspectBody.includes('c.id'), 'inspects item id');
    assert.ok(inspectBody.includes('hasSections:'), 'inspects sections 3 existence');
    assert.ok(inspectBody.includes('hasImage:'), 'inspects image existence');
    assert.ok(inspectBody.includes('totalSizeFormatted'), 'formats total data size');
  });

  // 8. Safety: executeCasesMigration NEVER deletes localStorage
  await test('8. Safety: executeCasesMigration NEVER calls removeItem or clear on healim_custom_cases', () => {
    const migrationMatch = mainJs.match(/async function executeCasesMigration\(\) \{([\s\S]*?)\n\}/);
    assert.ok(migrationMatch, 'executeCasesMigration exists');
    const migBody = migrationMatch[1];
    assert.ok(!migBody.includes("localStorage.removeItem('healim_custom_cases')"), 'Must NOT remove healim_custom_cases');
    assert.ok(!migBody.includes('localStorage.clear()'), 'Must NOT clear localStorage');
  });

  // 9. 3-Tier Security Defense
  await test('9. 3-Tier Security Defense: UI + Firestore Rules + Storage Rules', () => {
    // 1. UI: Reviews page has locked state for unauthenticated single views
    assert.ok(mainJs.includes("protectedWrapper.classList.add('is-locked')"), 'UI locks single view when unauthenticated');
    // 2. Firestore Public Previews: Anyone can read cards
    assert.ok(firestoreRules.includes('match /treatment_review_previews/{reviewId}'), 'treatment_review_previews exists');
    assert.ok(firestoreRules.includes('allow read: if true;'), 'Previews allow public read');
    // 3. Firestore Details: Read requires authenticated user
    assert.ok(firestoreRules.includes('match /treatment_reviews/{reviewId}'), 'treatment_reviews exists');
    assert.ok(firestoreRules.includes('allow read: if request.auth != null;'), 'Details restricted to authenticated user');
    // 4. Storage: Read requires authenticated user
    assert.ok(storageRules.includes('match /treatment-reviews/{reviewId}/{fileName}') && storageRules.includes('allow read: if signedIn();'), 'Storage restricts read to signedIn()');
  });

  // 10. Creation Flow: Atomic Two-Tier sync (Detail + Public Preview)
  await test('10. New case registration: Writes both treatment_reviews and treatment_review_previews atomically in batch', () => {
    const submitMatch = mainJs.match(/function handleAdminCaseSubmit\(e\) \{([\s\S]*?)\n\}/);
    assert.ok(submitMatch, 'handleAdminCaseSubmit exists');
    const submitBody = submitMatch[1];
    assert.ok(submitBody.includes('await storageRef.put(blob'), 'Uploads image blob to Storage first');
    assert.ok(submitBody.includes(".collection('treatment_reviews').doc(reviewId)"), 'Writes treatment_reviews detail document');
    assert.ok(submitBody.includes(".collection('treatment_review_previews').doc(reviewId)"), 'Writes treatment_review_previews public document');
    assert.ok(submitBody.includes('await batch.commit()'), 'Commits both documents atomically via batch');
    assert.ok(submitBody.includes('await storageRef.delete()'), 'Rolls back Storage upload on failure');
  });

  // 11. Deletion Flow: Atomic Two-Tier sync
  await test('11. Case deletion: Deletes from both collections and storage', () => {
    const deleteMatch = mainJs.match(/function deleteCurrentCustomCase\(\) \{([\s\S]*?)\n\}/);
    assert.ok(deleteMatch, 'deleteCurrentCustomCase exists');
    const deleteBody = deleteMatch[1];
    assert.ok(deleteBody.includes(".collection('treatment_reviews').doc(targetId)"), 'Deletes from treatment_reviews');
    assert.ok(deleteBody.includes(".collection('treatment_review_previews').doc(targetId)"), 'Deletes from treatment_review_previews');
    assert.ok(deleteBody.includes('await batch.commit()'), 'Batch commits deletion');
  });

  console.log(`\n==================================================`);
  console.log(`📊 Total Tests: ${passed} | Passed: ${passed} | Failed: 0`);
  console.log(`==================================================\n`);
}

run();
